export const OPTIMZE_TASK_BY_USER_REQUEST = 'OPTIMZE_TASK_BY_USER_REQUEST';
export const OPTIMZE_TASK_BY_USER_SUCCESS = 'OPTIMZE_TASK_BY_USER_SUCCESS';
export const OPTIMZE_TASK_BY_USER_FAILURE = 'OPTIMZE_TASK_BY_USER_FAILURE';