export const GAIA_SIGNIN_REQUEST = "GAIA_SIGNIN_REQUEST";
export const GAIA_SIGNIN_SUCCESS = "GAIA_SIGNIN_SUCCESS";
export const GAIA_SIGNIN_FAIL = "GAIA_SIGNIN_FAIL";

export const BOSS_SIGNIN_REQUEST = "BOSS_SIGNIN_REQUEST";
export const BOSS_SIGNIN_SUCCESS = "BOSS_SIGNIN_SUCCESS";
export const BOSS_SIGNIN_FAIL = "BOSS_SIGNIN_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";