package enums

var (
	AUTH_SERVICE = "AUTH_SERVICE"
	GAIA_SERVICE = "GAIA_SERVICE"
	TASK_MANAGER = "TASK_MANAGER"
	WORK_OPTIMIZATION = "WORK_OPTIMIZATION"
	SCHEDULE_PLAN = "SCHEDULE_PLAN"
	CAMERA_CV = "CAMERA_CV"
	NOTIFICATION = "NOTIFICATION"
)