// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthToken struct {
	ID         string `json:"id"`
	Token      string `json:"token"`
	TokenType  string `json:"tokenType"`
	ExpiryDate string `json:"expiryDate"`
	User       *User  `json:"user"`
}

type AuthTokenResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	Name         string `json:"name"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	LastLogin    string `json:"lastLogin"`
	BossType     string `json:"bossType"`
	Role         string `json:"role"`
	GaiaHealth   string `json:"gaiaHealth"`
}

type Comment struct {
	ID           string `json:"id"`
	Content      string `json:"content"`
	ActiveStatus string `json:"activeStatus"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
	Task         string `json:"task"`
}

type CreateGroupTaskInput struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Priority    []string `json:"priority"`
	Status      string   `json:"status"`
	ProjectID   string   `json:"projectId"`
	Tasks       []string `json:"tasks,omitempty"`
}

type CreateProjectInput struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       string `json:"status"`
	Color        string `json:"color"`
	OwnerID      string `json:"ownerId"`
	ActiveStatus string `json:"activeStatus"`
}

type CreateTaskInput struct {
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Priority     []string `json:"priority"`
	Status       string   `json:"status"`
	StartDate    string   `json:"startDate"`
	Deadline     string   `json:"deadline"`
	Duration     string   `json:"duration"`
	ActiveStatus string   `json:"activeStatus"`
	GroupTaskID  string   `json:"groupTaskId"`
}

type CreateUserInput struct {
	Name             string `json:"name"`
	Username         string `json:"username"`
	Email            string `json:"email"`
	Password         string `json:"password"`
	MatchingPassword string `json:"matchingPassword"`
}

type GenerateTaskWithoutGroupTaskInput struct {
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Priority     []string `json:"priority"`
	Status       string   `json:"status"`
	StartDate    string   `json:"startDate"`
	Deadline     string   `json:"deadline"`
	Duration     string   `json:"duration"`
	ActiveStatus string   `json:"activeStatus"`
	ProjectID    string   `json:"projectId"`
}

type GroupTask struct {
	ID             string   `json:"id"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Priority       []string `json:"priority"`
	Status         string   `json:"status"`
	OrdinalNumber  *int     `json:"ordinalNumber,omitempty"`
	ActiveStatus   string   `json:"activeStatus"`
	Project        string   `json:"project"`
	Tasks          []string `json:"tasks"`
	TotalTasks     *int     `json:"totalTasks,omitempty"`
	CompletedTasks *int     `json:"completedTasks,omitempty"`
	CreatedAt      string   `json:"createdAt"`
	UpdatedAt      string   `json:"updatedAt"`
}

type IDInput struct {
	ID string `json:"id"`
}

type ListAllUsers struct {
	ID        float64  `json:"id"`
	Name      string   `json:"name"`
	Username  string   `json:"username"`
	Email     string   `json:"email"`
	LastLogin string   `json:"lastLogin"`
	Roles     []string `json:"roles"`
}

type ListPrivilegeResponse struct {
	ID          float64             `json:"id"`
	Name        string              `json:"name"`
	Description *string             `json:"description,omitempty"`
	Roles       []*RoleOnlyResponse `json:"roles"`
}

type MoveTaskInput struct {
	OldGroupTaskID string `json:"oldGroupTaskId"`
	NewGroupTaskID string `json:"newGroupTaskId"`
	TaskID         string `json:"taskId"`
}

type Mutation struct {
}

type Privilege struct {
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type PrivilegeInput struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

type Project struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Status       string   `json:"status"`
	Color        string   `json:"color"`
	ActiveStatus string   `json:"activeStatus"`
	GroupTasks   []string `json:"groupTasks"`
	OwnerID      float64  `json:"ownerId"`
	CreatedAt    string   `json:"createdAt"`
	UpdatedAt    string   `json:"updatedAt"`
}

type ProjectGroupTaskIDInput struct {
	ProjectID   string `json:"projectId"`
	GroupTaskID string `json:"groupTaskId"`
}

type Query struct {
}

type Role struct {
	ID          float64      `json:"id"`
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Privileges  []*Privilege `json:"privileges"`
}

type RoleInput struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

type RoleOnlyResponse struct {
	ID          float64 `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type SigninInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SubTask struct {
	ID           string   `json:"id"`
	Mission      string   `json:"mission"`
	Deadline     string   `json:"deadline"`
	Priority     []string `json:"priority"`
	Status       string   `json:"status"`
	ActiveStatus string   `json:"activeStatus"`
	CreatedAt    string   `json:"createdAt"`
	UpdatedAt    string   `json:"updatedAt"`
	Task         string   `json:"task"`
}

type Task struct {
	ID           string   `json:"id"`
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Priority     []string `json:"priority"`
	Status       string   `json:"status"`
	StartDate    string   `json:"startDate"`
	Deadline     string   `json:"deadline"`
	Duration     float64  `json:"duration"`
	ActiveStatus string   `json:"activeStatus"`
	CreatedAt    string   `json:"createdAt"`
	UpdatedAt    string   `json:"updatedAt"`
	GroupTask    string   `json:"groupTask"`
	SubTasks     []string `json:"subTasks"`
	Comments     []string `json:"comments"`
}

type TaskDashboard struct {
	DoneTaskList    []*Task `json:"doneTaskList"`
	NotDoneTaskList []*Task `json:"notDoneTaskList"`
}

type TokenInput struct {
	Token string `json:"token"`
}

type TokenResponse struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	AccessToken string `json:"accessToken"`
	ExpiryDate  string `json:"expiryDate"`
}

type UpdateColorInput struct {
	ID    string `json:"id"`
	Color string `json:"color"`
}

type UpdateGroupTaskInput struct {
	GroupTaskID string   `json:"groupTaskId"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Priority    []string `json:"priority"`
	Status      string   `json:"status"`
	ProjectID   string   `json:"projectId"`
	Tasks       []string `json:"tasks,omitempty"`
}

type UpdateObjectNameInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateProjectInput struct {
	ProjectID    string `json:"projectId"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       string `json:"status"`
	Color        string `json:"color"`
	OwnerID      string `json:"ownerId"`
	ActiveStatus string `json:"activeStatus"`
}

type UpdateTaskInDialogInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	TaskID      string `json:"taskId"`
}

type UpdateTaskInput struct {
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Priority     []string `json:"priority"`
	Status       string   `json:"status"`
	StartDate    string   `json:"startDate"`
	Deadline     string   `json:"deadline"`
	Duration     string   `json:"duration"`
	ActiveStatus string   `json:"activeStatus"`
	TaskID       string   `json:"taskId"`
}

type UpdateUser struct {
	ID        float64  `json:"id"`
	Name      string   `json:"name"`
	Username  string   `json:"username"`
	Email     string   `json:"email"`
	LastLogin string   `json:"lastLogin"`
	Roles     []string `json:"roles"`
}

type UpdateUserInput struct {
	UserID   float64  `json:"userId"`
	Name     string   `json:"name"`
	Username string   `json:"username"`
	Email    string   `json:"email"`
	Roles    []string `json:"roles"`
}

type User struct {
	ID         float64 `json:"id"`
	Name       string  `json:"name"`
	Username   string  `json:"username"`
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	LastLogin  string  `json:"lastLogin"`
	Enabled    bool    `json:"enabled"`
	IsUsing2fa bool    `json:"isUsing2FA"`
	Secret     string  `json:"secret"`
	Roles      []*Role `json:"roles"`
}

type UserInput struct {
	ID       float64 `json:"id"`
	Name     string  `json:"name"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
}

type UserPermissionInput struct {
	UserID       string `json:"userId"`
	PermissionID string `json:"permissionId"`
}

type UserPermissionResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
